const app=document.querySelector('#app'), dialog=document.querySelector('#dialog');
const roles={elder:'老人',family:'家属',operator:'运营'};
const labels={pending:'待接单',accepted:'已接单',in_progress:'服务中',awaiting_feedback:'待回访',closed:'已完成',cancelled:'已取消'};
const navigation=[['home','layout-dashboard','今日'],['services','hand-heart','预约服务'],['health','heart-pulse','健康记录'],['wallet','wallet','财富守护'],['together','users','精神陪伴'],['orders','clipboard-list','我的预约'],['profile','contact-round','档案与授权']];
let state=null, token=CareSession.getItem('eldercare-token'), role=CareSession.getItem('eldercare-role')||'elder';
let route=location.hash.slice(1)||'home', filter='全部', busy=false, offline=false, generation=0, toastTimer;
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const icon=name=>`<i data-lucide="${name}" aria-hidden="true"></i>`;
const btn=(label,action,kind='primary',extra='')=>`<button class="btn ${kind}" data-action="${action}" ${extra}>${label}</button>`;
const symbol=(name,color='green')=>`<span class="symbol ${color}">${icon(name)}</span>`;
const badge=s=>`<span class="badge ${s}">${labels[s]||h(s)}</span>`;
const empty=(title,desc='')=>`<div class="empty">${icon('inbox')}<h3>${title}</h3>${desc?`<p>${desc}</p>`:''}</div>`;
const denied=()=>empty('这项信息尚未授权','请由老人本人在「档案与授权」中确认共享范围。');
const field=(label,name,type='text',value='',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" value="${h(value)}" ${extra} required></label>`;
const options=values=>values.map(x=>`<option>${h(x)}</option>`).join('');
const select=(label,name,values)=>`<label class="field">${label}<select name="${name}">${options(values)}</select></label>`;
const memo=(label='补充说明',name='note',required=false)=>`<label class="field">${label}<textarea name="${name}" maxlength="200" ${required?'required':''}></textarea></label>`;
const shortDate=value=>value?.slice(5).replace('-','月')+'日';
const actions=(label='保存')=>`<p class="inline-error" id="form-error" role="alert"></p><div class="form-actions">${btn('取消','close','secondary')}<button class="btn primary" type="submit">${label}</button></div>`;
const monthLedger=()=>state.ledger?.filter(x=>x.date.startsWith(state.today.slice(0,7)))||[];
const spending=()=>monthLedger().filter(x=>x.type==='expense').reduce((a,b)=>a+b.amount,0);
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.style.display='none',4200);}
function paintIcons(){window.lucide?.createIcons();}
async function api(path,options={}){return PublicCareAPI.request(path,options,token);}
async function enter(nextRole){const g=++generation;try{const data=await api('session',{method:'POST',body:JSON.stringify({role:nextRole})});if(g!==generation)return;token=data.token;role=nextRole;state=data.state;CareSession.setItem('eldercare-token',token);CareSession.setItem('eldercare-role',role);route='home';filter='全部';location.hash='home';offline=false;dialog.close();render();}catch(error){toast(error.message);}}
async function run(action,data={}){if(busy)return null;busy=true;const g=generation;document.querySelectorAll('button[type=submit]').forEach(x=>x.disabled=true);try{const result=await api('command',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({action,data})});if(g!==generation)return null;state=result.state;offline=false;render();return result;}catch(error){if(error.status===403)await refresh();throw error;}finally{busy=false;document.querySelectorAll('button[type=submit]').forEach(x=>x.disabled=false);}}
async function refresh(){if(!token)return;const g=generation;try{const next=await api('state');if(g!==generation)return;const changed=!state||state.revision!==next.revision;state=next;if(offline||changed){offline=false;render();}}catch(error){if(g!==generation)return;offline=true;render();}}
function go(next){route=next;filter='全部';location.hash=next;dialog.close();render();window.scrollTo({top:0});}
function heading(title,subtitle='',right=''){return `<div class="page-heading between"><div><div class="eyebrow">${role==='operator'?'服务运营中心':role==='family'?'家属照护空间':'我的照护空间'}</div><h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div>${right}</div>`;}
function head(title,link='',action=''){return `<div class="section-head between"><h2>${title}</h2>${link?`<button class="text-btn" data-action="${action}">${link}${icon('chevron-right')}</button>`:''}</div>`;}
function metrics(items){return `<div class="metrics">${items.map(x=>`<div class="metric">${symbol(x[3],x[4]||'green')}<div><div class="label">${x[0]}</div><strong>${h(x[1])}</strong><span class="unit">${x[2]}</span></div></div>`).join('')}</div>`;}
function tasksList(){const items=(state.tasks||[]).filter(x=>x.date===state.today).sort((a,b)=>a.time.localeCompare(b.time));return items.length?`<div class="surface task-list">${items.map(x=>`<div class="task ${x.done?'done':''}"><button class="task-check ${x.done?'checked':''}" aria-label="${x.done?'取消完成':'完成'}${h(x.title)}" aria-pressed="${x.done}" data-action="task-toggle" data-id="${h(x.id)}">${x.done?icon('check'):''}</button><div><div class="task-title">${h(x.title)}</div><div class="task-time">${x.time}</div></div><span class="task-tag">${h(x.kind)}</span></div>`).join('')}</div>`:empty('今天还没有安排');}
function orderRow(x){return `<div class="order-row"><div class="between"><h3>${h(x.serviceName)}</h3>${badge(x.status)}</div><p>${icon('calendar-days')} ${h(x.date)} ${h(x.time)}</p><p>${h(x.address)}</p><div class="between" style="margin-top:12px"><span class="footnote">${x.assignee?'承接人：'+h(x.assignee):'等待安排承接人'}</span><button class="text-btn" data-action="order-detail" data-id="${h(x.id)}">查看进度${icon('arrow-up-right')}</button></div></div>`;}
function home(){if(role==='operator')return operations();const todo=(state.tasks||[]).filter(x=>x.date===state.today&&!x.done).length;const count=(state.orders||[]).filter(x=>!['closed','cancelled'].includes(x.status)).length;const last=state.health?.slice().sort((a,b)=>a.date.localeCompare(b.date)).at(-1);return `${heading(role==='elder'?`${h(state.profile.name)}，今天也要照顾好自己`:`一起照顾好${h(state.profile.name)}`,'每一份关心，都有回应。',`<div class="date-display"><strong>${new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric'})}</strong>${new Date().toLocaleDateString('zh-CN',{weekday:'long'})}</div>`)}${metrics([['今日待办',state.tasks?todo:'—','项','list-checks'],['进行中的预约',state.orders?count:'—','项','calendar-check','gold'],['已报名活动',state.enrollments?.length??'—','场','users','blue']])}<div class="columns"><div class="stack"><section>${head('今日安排','添加安排','task-add')}${state.tasks?tasksList():denied()}</section><section>${head('需要时，有人搭把手','全部服务','nav-services')}<div class="service-shortcuts">${state.services.map(s=>`<button class="shortcut" data-action="book" data-id="${s.id}">${symbol(s.icon,s.color)}<strong>${s.name}</strong><span class="muted">${s.duration}</span></button>`).join('')}</div></section><section>${head('预约进度','全部预约','nav-orders')}${state.orders?.length?`<div class="surface">${state.orders.filter(x=>!['closed','cancelled'].includes(x.status)).slice(0,2).map(orderRow).join('')||empty('暂无进行中的预约')}</div>`:empty('暂无预约记录')}</section></div><aside class="stack"><section>${head('最近健康记录')}${last?`<div class="health-summary"><div class="between"><strong>血压与脉搏</strong><span class="badge">${h(last.source)}</span></div><div class="health-numbers"><div><strong>${last.systolic}<span class="muted"> / </span>${last.diastolic}</strong><small>血压 · mmHg</small></div><div class="divider"></div><div><strong>${last.pulse}</strong><small>脉搏 · 次/分</small></div></div><div class="between"><span class="footnote">${h(last.date)}<br>仅记录，不作诊断</span>${btn('记录读数','health-add','secondary small')}</div></div>`:state.health?empty('还没有健康记录'):denied()}</section><section>${role==='elder'?`<button class="assistant-entry" data-action="assistant">${symbol('message-circle-heart')}<div><strong>有什么需要帮忙？</strong><p>本地服务助手</p></div>${icon('chevron-right')}</button>`:`<div class="note-band"><div class="row">${icon('shield-check')}<strong>尊重每一次授权</strong></div><p class="footnote" style="margin-top:9px">${h(state.profile.name)}的收支和陪伴聊天不会默认向您开放。</p></div>`}</section><section class="note-band"><div class="row">${symbol('phone','gold')}<div><h3>给家人一个电话</h3><p class="footnote">${state.profile.phone?h(state.profile.phone):'还未填写家属联系电话'}</p></div></div><div style="margin-top:15px">${btn('联系家属','contact','secondary full')}</div></section><button class="text-btn" data-action="read-today">${icon('volume-2')}朗读今日安排</button></aside></div>`;}
function services(){const list=state.services.filter(s=>filter==='全部'||s.category===filter);return `${heading('把需要的照护，安排好','确认服务、时间与地点后，再提交预约。') }<div class="notice">公开体验目录 · 服务机构、价格和名额均为示例；提交不会联系真实机构，也不会扣费。</div><div class="filters">${['全部','康养照护','生活照料','精神陪伴'].map(x=>`<button class="chip ${filter===x?'active':''}" data-action="filter" data-value="${x}">${x}</button>`).join('')}</div><div class="service-grid">${list.map(s=>`<article class="service-item"><div class="row">${symbol(s.icon,s.color)}<div><h3>${s.name}</h3><div class="service-meta"><span>${s.duration}</span><span>${s.category}</span></div></div></div><p class="desc">${s.desc}</p><div class="between"><div class="price">${s.price?'¥'+money(s.price):'免费'}<small> / ${s.unit} · 示例价</small></div>${btn('预约','book','primary',`data-id="${s.id}"`)}</div><p class="boundary">${s.boundary}</p></article>`).join('')}</div>`;}
function health(){if(!state.health)return heading('健康记录')+denied();const recent=state.health.slice().sort((a,b)=>a.date.localeCompare(b.date)).slice(-7),last=recent.at(-1);return `${heading('健康记录，心中有数','记录设备实际读数，保留每一天的变化。',btn(icon('plus')+'记录读数','health-add'))}${metrics([['最近收缩压',last?.systolic||'—','mmHg','activity'],['最近舒张压',last?.diastolic||'—','mmHg','heart','gold'],['最近脉搏',last?.pulse||'—','次/分','heart-pulse','coral']])}<div class="columns"><section>${head('最近7次血压记录')}${recent.length?`<div class="chart" role="img" aria-label="最近七次收缩压和舒张压趋势">${recent.map(x=>`<div class="bar-group"><div class="bar" style="height:${x.systolic/300*100}%"><span>${x.systolic}</span></div><div class="bar low" style="height:${x.diastolic/300*100}%"><span>${x.diastolic}</span></div></div>`).join('')}</div><div class="chart-labels">${recent.map(x=>`<span>${x.date.slice(5)}</span>`).join('')}</div><div class="legend"><span>收缩压（mmHg）</span><span>舒张压（mmHg）</span></div>`:empty('还没有测量记录')}<h2 class="table-title">记录明细</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>日期</th><th>血压 mmHg</th><th>脉搏 次/分</th><th>来源</th></tr></thead><tbody>${state.health.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,30).map(x=>`<tr><td>${x.date}</td><td>${x.systolic} / ${x.diastolic}</td><td>${x.pulse}</td><td>${x.source}</td></tr>`).join('')}</tbody></table></div></section><aside class="stack"><section>${head('今日安排','添加','task-add')}${tasksList()}</section><div class="notice">记录不构成诊断或用药建议。如有不适，请联系医务人员。当前未接入监测设备，所有新增读数均为手动填写。</div></aside></div>`;}
function wallet(){if(!state.ledger)return heading('财富守护')+denied();const spent=spending(),income=monthLedger().filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0);return `${heading('每一笔收支，都记得清楚','账本仅记录，不连接银行卡、不代客交易。',btn(icon('plus')+'记一笔','ledger-add'))}${metrics([['本月支出',money(spent),'元','arrow-up-right','gold'],['本月收入',money(income),'元','arrow-down-left'],['剩余预算',money(state.budget-spent),'元','wallet','blue']])}<div class="columns"><section>${head('本月收支')}<div class="filters">${['全部','支出','收入'].map(x=>`<button class="chip ${filter===x?'active':''}" data-action="filter" data-value="${x}">${x}</button>`).join('')}</div>${monthLedger().filter(x=>filter==='全部'||x.type===(filter==='收入'?'income':'expense')).sort((a,b)=>b.date.localeCompare(a.date)).map(x=>`<div class="ledger-row">${symbol(x.type==='income'?'arrow-down-left':'shopping-basket',x.type==='income'?'green':'gold')}<div><strong>${h(x.category)}</strong><p>${h(x.note||'未填写备注')} · ${shortDate(x.date)}</p></div><strong class="amount ${x.type}">${x.type==='income'?'+':'−'}${money(x.amount)}</strong><button class="icon-btn" title="删除这笔记录" aria-label="删除这笔记录" data-action="ledger-delete" data-id="${h(x.id)}">${icon('trash-2')}</button></div>`).join('')||empty('本月暂无这类记录')}</section><aside class="stack"><section class="budget"><div class="between"><h3>本月生活预算</h3><button class="icon-btn" data-action="budget" title="修改月预算" aria-label="修改月预算">${icon('pencil')}</button></div><strong>¥ ${money(state.budget)}</strong><div class="progress"><span style="width:${Math.min(spent/state.budget*100,100)}%"></span></div><p class="footnote">${spent>state.budget?'已超出预算 ¥'+money(spent-state.budget):'已使用 '+Math.round(spent/state.budget*100)+'%'}</p></section><section>${head('把钱袋子守好')}<article class="article"><h3>验证码，不告诉陌生人</h3><p>遇到索要验证码或要求屏幕共享，先暂停，再通过官方渠道核实。</p></article><article class="article"><h3>“保本高收益”，先别着急</h3><p>不跟随陌生链接转账，和可信家属商量，核对产品与机构信息。</p></article><p class="footnote" style="margin-top:15px">以上为一般安全提示，不作具体交易、收益或诈骗认定。</p></section></aside></div>`;}
function together(){if(!state.enrollments)return heading('精神陪伴')+denied();const mood=state.moods.find(x=>x.date===state.today)?.mood;return `${heading('日子里，总有新的相遇','和家人聊聊，也和邻里坐坐。')}<div class="columns"><div class="stack">${role==='elder'?`<section>${head('今天心情怎么样？')}<div class="mood-picker">${[['开心','smile'],['平静','meh'],['有点低落','cloud']].map(([x,i])=>`<button class="mood ${mood===x?'active':''}" data-action="mood" data-value="${x}" aria-pressed="${mood===x}">${icon(i)}${x}</button>`).join('')}</div>${mood?`<p class="footnote" style="margin-top:12px">今天记录了「${mood}」。</p>`:''}</section>`:`<section>${head('最近的心情')}<p>${mood?'今天：'+mood:'今天还没有记录'}</p></section>`}<section>${head('社区活动')}<p class="footnote">活动与名额为示例，报名仅保存在当前浏览器。</p>${state.activities.map(x=>`<article class="activity">${symbol(x.icon,x.color)}<div><h3>${x.name}</h3><p>${x.date} ${x.time} · ${x.place}</p><p>剩余 ${x.capacity-x.booked-(state.enrollments.includes(x.id)?1:0)} 个名额</p></div>${btn(state.enrollments.includes(x.id)?'取消报名':'报名参加','activity','secondary small',`data-id="${x.id}"`)}</article>`).join('')}</section></div><aside class="stack"><section class="health-summary"><div class="row">${icon('phone')}<h3>一通电话，一份安心</h3></div><p style="margin:15px 0" class="muted">${h(state.profile.family)} · ${h(state.profile.relationship)}</p>${btn('联系家属','contact','primary full')}</section>${role==='elder'?`<section>${head('本地服务助手')}<p class="muted" style="font-size:14px;margin-bottom:18px">今天想安排些什么？</p>${btn(icon('message-circle')+'聊一聊','assistant','secondary full')}<p class="footnote" style="margin-top:12px">规则式服务引导，未接入大模型。不替代亲情或专业心理服务。</p></section>`:''}</aside></div>`;}
function orders(){if(!state.orders)return heading('我的预约')+denied();const list=state.orders.filter(x=>filter==='全部'||labels[x.status]===filter);return `${heading(role==='operator'?'服务工单':'我的预约','从预约到回访，每一步都有记录。',role==='operator'?'':btn(icon('plus')+'预约服务','nav-services'))}<div class="filters">${['全部',...Object.values(labels)].map(x=>`<button class="chip ${filter===x?'active':''}" data-action="filter" data-value="${x}">${x}</button>`).join('')}</div>${list.length?`<div class="surface">${list.map(orderRow).join('')}</div>`:empty('暂无此状态的预约')}`;}
function operations(){const orders=state.orders||[];return `${heading('今天的服务，逐件落实','运营体验身份 · 仅显示履约所需的预约信息。')}${metrics([['等待接单',orders.filter(x=>x.status==='pending').length,'单','inbox','gold'],['履约中',orders.filter(x=>['accepted','in_progress'].includes(x.status)).length,'单','clipboard-check'],['等待回访',orders.filter(x=>x.status==='awaiting_feedback').length,'单','message-square','blue']])}<div class="notice">本地演示工单不会通知真实服务人员。操作后，可切换老人或家属视图查看同步结果。</div>${head('待处理工单','全部工单','nav-orders')}${orders.filter(x=>!['closed','cancelled'].includes(x.status)).map(orderRow).join('')||empty('当前没有待处理工单')}`;}
function profile(){if(role==='operator')return heading('运营权限')+`<div class="notice">此身份可以接单、登记承接人、记录服务过程；不能访问老人健康读数、收支账本或私人聊天。</div>${audit()}`;return `${heading('我的档案与授权','共享给谁、共享什么，由本人决定。')}<div class="columns"><div><div class="profile-banner"><div class="avatar">${h(state.profile.name.slice(0,1))}</div><div><h2>${h(state.profile.name)}</h2><p>${state.profile.age}岁 · ${h(state.profile.community)}</p></div>${role==='elder'?`<button class="icon-btn push" data-action="profile-edit" title="编辑档案" aria-label="编辑档案">${icon('pencil')}</button>`:''}</div><dl class="detail-grid"><div><dt>家庭联系人</dt><dd>${h(state.profile.family)}（${h(state.profile.relationship)}）</dd></div><div><dt>联系电话</dt><dd>${h(state.profile.phone||'尚未填写')}</dd></div><div><dt>服务地址</dt><dd>${h(state.profile.address)}</dd></div><div><dt>数据环境</dt><dd>当前浏览器保存 · 示例数据</dd></div></dl>${head('家属授权范围')}<p class="footnote">公开体验中可随时撤回；真实线上身份绑定尚未接入。</p>${[['health','健康记录与日常安排','查看读数、添加安排与标记完成'],['booking','预约协助与服务跟进','创建和取消预约、查看履约进度'],['finance','收支账本与预算','查看、登记和删除收支记录'],['companionship','心情与社区活动','查看心情、协助活动报名；不含私聊']].map(([k,t,d])=>`<label class="settings-row"><div><strong>${t}</strong><p>${d}</p></div><input class="switch" type="checkbox" data-grant="${k}" ${state.grants[k]?'checked':''} ${role==='elder'?'':'disabled'} aria-label="${t}授权"></label>`).join('')}</div><aside class="stack"><section>${head('阅读与数据')}<label class="settings-row"><strong>大字模式</strong><input class="switch" type="checkbox" id="large-mode" ${CarePreferences.getItem('eldercare-large')==='1'?'checked':''}></label><div style="margin:20px 0">${btn(icon('download')+'导出当前授权数据','export','secondary full')}</div><p class="footnote">导出文件可能包含健康或收支信息，请妥善保存。</p></section><section>${head('接入状态')}<div class="settings-row"><span>本浏览器内的操作与记录</span><span class="badge">可用</span></div><div class="settings-row"><span>真实微信账号</span><span class="badge pending">未接入</span></div><div class="settings-row"><span>大模型 / 监测设备</span><span class="badge pending">未接入</span></div><div class="settings-row"><span>支付 / 机构通知</span><span class="badge pending">未接入</span></div></section>${audit()}</aside></div>`;}
function audit(){return `<section>${head('最近操作记录')}<div>${state.audit.slice(0,5).map(x=>`<div class="article"><p>${h({'grant.set':'调整家属授权','order.create':'提交预约','order.transition':'更新履约状态','health.add':'新增健康记录','order.review':'回访归档','ledger.add':'新增收支','task.toggle':'更新日常安排'}[x.action]||'更新照护记录')}</p><small class="muted">${roles[x.actor]} · ${new Date(x.at).toLocaleString('zh-CN')}</small></div>`).join('')||'<p class="footnote">还没有操作记录</p>'}</div></section>`;}
function render(){if(!state)return;if(role==='operator'&&!['home','orders','profile'].includes(route))route='home';if(!navigation.some(x=>x[0]===route))route='home';document.body.classList.toggle('large',CarePreferences.getItem('eldercare-large')==='1');const nav=role==='operator'?navigation.filter(x=>['home','orders','profile'].includes(x[0])):navigation;app.innerHTML=`<div class="shell"><aside class="sidebar"><a class="brand" href="#home"><span class="brand-mark">${icon('heart-handshake')}</span><div><div class="brand-name">智慧养老</div><div class="brand-sub">财富 · 康养 · 陪伴</div></div></a><div class="nav-label">${role==='operator'?'服务运营':'我的空间'}</div><nav class="nav">${nav.map(([id,i,label])=>`<a href="#${id}" class="${route===id?'active':''}" ${route===id?'aria-current="page"':''}>${icon(i)}${role==='operator'&&id==='home'?'运营工作台':label}</a>`).join('')}</nav><div class="sidebar-bottom"><button class="text-btn emergency" data-action="emergency">${icon('phone-call')}紧急求助</button><p>公开体验版 · 示例数据<br>勿填真实敏感资料</p><div class="mini-profile row" style="margin-top:20px"><div class="avatar">${role==='operator'?'运':h(state.profile.name.slice(0,1))}</div><div><strong style="font-size:14px">${role==='operator'?'运营体验账号':h(state.profile.name)}</strong><p style="margin-top:3px">${roles[role]}视图</p></div></div></div></aside><header class="topbar"><span class="context"><span class="demo-dot"></span>公开体验 · 示例数据</span><div class="row"><div class="role-switch" aria-label="切换体验身份">${Object.entries(roles).map(([k,v])=>`<button data-role="${k}" class="${role===k?'active':''}" aria-pressed="${role===k}">${v}视图</button>`).join('')}</div><button class="icon-btn" data-action="emergency" title="紧急求助" aria-label="紧急求助">${icon('phone')}</button></div></header>${offline?'<div class="offline-banner">体验记录暂时无法读取，请刷新页面或检查浏览器存储权限。</div>':''}<main class="content">${({home,services,health,wallet,together,orders,profile}[route])()}</main><nav class="mobile-nav" aria-label="主要导航">${(role==='operator'?nav:[navigation[0],navigation[1],navigation[2],navigation[4],navigation[6]]).map(([id,i,l])=>`<a href="#${id}" class="${route===id?'active':''}">${icon(i)}${({services:'服务',health:'健康',together:'陪伴',profile:'我的'})[id]||l}</a>`).join('')}</nav></div>`;paintIcons();}
function modal(title,body){dialog.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${title}</h2><button class="icon-btn" data-action="close" aria-label="关闭">${icon('x')}</button></div><div class="dialog-body">${body}</div>`;if(!dialog.open)dialog.showModal();paintIcons();}
function formModal(title,contents,action,extra={},label='保存'){modal(title,`<form id="modal-form">${contents}${actions(label)}</form>`);document.querySelector('#modal-form').onsubmit=async e=>{e.preventDefault();try{const result=await run(action,{...Object.fromEntries(new FormData(e.target)),...extra});if(result){dialog.close();toast(result.message);}}catch(error){document.querySelector('#form-error').textContent=error.message;}};}
function confirm(title,message,action,data,label='确认'){formModal(title,`<p>${message}</p>`,action,data,label);}
function orderDetail(id){const o=state.orders?.find(x=>x.id===id);if(!o)return toast('记录不在当前授权范围');let buttons='';if(role==='operator'){const next={pending:['accepted','接单并安排'],accepted:['in_progress','开始服务'],in_progress:['awaiting_feedback','完成服务并回访']}[o.status];if(next)buttons=btn(next[1],'order-process','primary',`data-id="${h(id)}" data-value="${next[0]}"`);}else{if(['pending','accepted'].includes(o.status))buttons=btn('取消预约','order-cancel','danger',`data-id="${h(id)}"`);if(o.status==='awaiting_feedback')buttons=btn('确认并回访','order-review','primary',`data-id="${h(id)}"`);}modal('预约详情',`<div class="between"><h3>${h(o.serviceName)}</h3>${badge(o.status)}</div><dl class="detail-grid"><div><dt>预约时间</dt><dd>${h(o.date)} ${h(o.time)}</dd></div><div><dt>示例费用（未支付）</dt><dd>¥ ${money(o.price)}</dd></div><div><dt>服务地点</dt><dd>${h(o.address)}</dd></div><div><dt>承接人</dt><dd>${h(o.assignee||'待安排')}</dd></div></dl><p>${h(o.note)}</p><div class="timeline">${o.timeline.map(t=>`<div class="timeline-item"><strong>${h(t.label)}</strong><small>${h(t.actor)} · ${new Date(t.at).toLocaleString('zh-CN')}</small>${t.note?`<p>${h(t.note)}</p>`:''}</div>`).join('')}</div>${o.review?`<p>回访评分：${o.review.rating} / 5<br>${h(o.review.note)}</p>`:''}<div class="form-actions">${buttons}</div>`);}
function assistant(){modal('本地服务助手',`<p class="footnote">规则式引导，未接入大模型；不会自动预约或拨打电话。</p><div id="chat-log">${(state.messages||[]).slice(-5).map(x=>`<div class="chat-item"><p class="question">${h(x.question)}</p><p class="answer">${h(x.answer)}</p><button class="text-btn" data-action="nav-${x.route}">前往办理${icon('arrow-right')}</button></div>`).join('')||'<p style="margin-top:20px">您好。今天有什么需要我帮您找到的？</p>'}</div><div class="quick-prompts">${['我想预约陪同就医','查看健康记录','看看社区活动'].map(x=>`<button data-action="prompt" data-value="${x}">${x}</button>`).join('')}</div><form id="chat-form" class="chat-input"><input name="message" aria-label="输入您的需要" placeholder="说说您的需要…" maxlength="300" required><button type="submit" class="btn primary" aria-label="发送">${icon('send')}</button></form><p id="chat-error" class="inline-error" role="alert"></p>`);document.querySelector('#chat-form').onsubmit=async e=>{e.preventDefault();await sendChat(new FormData(e.target).get('message'));};}
async function sendChat(message){try{const res=await run('assistant.send',{message});if(res){assistant();dialog.querySelector('.dialog-body').scrollTop=10000;}}catch(e){document.querySelector('#chat-error').textContent=e.message;}}
async function onAction(button){const a=button.dataset.action,id=button.dataset.id,value=button.dataset.value;if(a?.startsWith('nav-')){const target=a.slice(4);if(target==='emergency')return emergency();go(target);return;}switch(a){
  case 'close':dialog.close();break;
  case 'filter':filter=value;render();break;
  case 'task-toggle':{const r=await run('task.toggle',{id});if(r)toast(r.message);break;}
  case 'task-add':formModal('添加日常安排',field('安排内容','title','text','','maxlength="40"')+`<div class="form-grid">${field('日期','date','date',state.today)}${field('时间','time','time','09:00')}</div>`,'task.add');break;
  case 'health-add':formModal('记录测量读数',`<p class="footnote" style="margin-bottom:18px">按设备实际读数填写，不作诊断。</p>${field('测量日期','date','date',state.today,`max="${state.today}"`)}<div class="form-grid">${field('收缩压（mmHg）','systolic','number','','min="30" max="300"')}${field('舒张压（mmHg）','diastolic','number','','min="20" max="200"')}</div>${field('脉搏（次/分）','pulse','number','','min="20" max="250"')}`,'health.add');break;
  case 'book':{if(role==='family'&&!state.grants.booking)return toast('老人尚未授权预约协助');const s=state.services.find(x=>x.id===id);const d=new Date();d.setDate(d.getDate()+1);const tomorrow=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;formModal(`预约${s.name}`,`<div class="notice">示例价 ¥${money(s.price)} / ${s.unit}，本次只登记预约，不会扣费或通知真实机构。</div><div class="form-grid">${field('服务日期','date','date',tomorrow,`min="${state.today}"`)}${field('开始时间','time','time','09:00')}</div>${field('服务地点','address','text',state.profile.address,'maxlength="100"')}${memo('补充需求（选填）')}<label class="row footnote"><input type="checkbox" required>已核对时间、地点和示例费用</label>`,'order.create',{serviceId:id},'确认预约');break;}
  case 'order-detail':orderDetail(id);break;
  case 'order-cancel':confirm('取消预约','确认取消这次预约？已取消的预约仍保留记录。','order.cancel',{id},'确认取消');break;
  case 'order-process':formModal(value==='accepted'?'安排承接人':value==='in_progress'?'开始服务':'登记完成情况',(value==='accepted'?field('承接人','assignee','text','','maxlength="30"'):'')+memo('处理记录','note',true),'order.transition',{id,status:value},'确认更新');break;
  case 'order-review':formModal('回访与评价',select('服务评分','rating',['5','4','3','2','1'])+memo('服务感受 / 待改进事项','note',true),'order.review',{id},'确认并归档');break;
  case 'ledger-add':formModal('记一笔',`<label class="field">收支类型<select name="type"><option value="expense">支出</option><option value="income">收入</option></select></label>${field('金额（元）','amount','number','','min="0.01" max="1000000" step="0.01"')}${select('分类','category',['日常生活','养老服务','医疗健康','兴趣活动','养老金','其他'])}${field('日期','date','date',state.today,`max="${state.today}"`)}${memo('备注（选填）')}`,'ledger.add');break;
  case 'ledger-delete':confirm('删除收支记录','确认删除这笔记录？此操作无法撤销。','ledger.delete',{id},'确认删除');break;
  case 'budget':formModal('设置月预算',field('每月预算（元）','amount','number',state.budget/100,'min="1" max="1000000" step="0.01"'),'budget.set');break;
  case 'activity':confirm(state.enrollments.includes(id)?'取消活动报名':'确认活动报名',state.enrollments.includes(id)?'确认取消本次活动报名？':'该活动为本地示例，报名不会发送给真实社区。','activity.toggle',{id});break;
  case 'mood':{const r=await run('mood.set',{mood:value});if(r)toast('今天的心情已记录');break;}
  case 'profile-edit':formModal('编辑我的档案',field('称呼','name','text',state.profile.name,'maxlength="15"')+field('服务地址','address','text',state.profile.address,'maxlength="100"')+`<label class="field">家属联系电话（选填）<input name="phone" type="tel" value="${h(state.profile.phone)}" maxlength="11" inputmode="numeric" pattern="1[3-9][0-9]{9}"></label>`,'profile.set');break;
  case 'contact':if(state.profile.phone)modal('联系家属',`<p>确认使用本机电话功能联系 ${h(state.profile.family)}：${h(state.profile.phone)}？</p><p class="footnote" style="margin-top:12px">仅打开拨号程序，不代表已经接通。</p><div class="form-actions"><a class="btn primary" href="tel:${h(state.profile.phone)}">打开拨号</a></div>`);else modal('还没有家属号码',`<p>请由老人本人在「我的档案与授权」中填写家庭联系人号码。</p><div class="form-actions">${btn('前往档案','nav-profile')}</div>`);break;
  case 'emergency':emergency();break;
  case 'read-today':if(!('speechSynthesis' in window))return toast('当前浏览器不支持朗读');speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance((state.tasks||[]).filter(x=>x.date===state.today).map(x=>`${x.time}，${x.title}，${x.done?'已完成':'待完成'}`).join('。')||'今天暂无安排');speech.lang='zh-CN';speech.rate=.85;speechSynthesis.speak(speech);toast('已开始朗读');break;
  case 'assistant':assistant();break;
  case 'prompt':await sendChat(value);break;
  case 'export':confirmExport();break;
}}
function emergency(){modal('紧急求助',`<div class="notice">本平台未接入紧急救援调度，不会自动报警或通知家属。</div><p>如遇人身危险或急病，请立即联系身边的人及当地紧急服务。</p><div class="form-actions"><a class="btn danger" href="tel:120">${icon('phone')}拨打120</a>${role!=='operator'?btn('联系家属','contact','secondary'):''}</div><p class="footnote" style="margin-top:18px">点击后打开本机拨号程序，仍需您确认拨号。</p>`);}
function confirmExport(){modal('导出当前数据',`<p>仅导出当前角色获授权查看的数据。文件可能包含敏感信息，请只保存在可信设备。</p><div class="form-actions">${btn('取消','close','secondary')}<button class="btn primary" id="confirm-export">确认导出</button></div>`);document.querySelector('#confirm-export').onclick=async()=>{await refresh();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`智慧养老-${roles[role]}-${state.today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);dialog.close();toast('数据已导出');};}
document.addEventListener('click',async e=>{const r=e.target.closest('[data-role]');if(r){await enter(r.dataset.role);return;}const b=e.target.closest('[data-action]');if(!b)return;e.preventDefault();try{await onAction(b);}catch(error){toast(error.message);}});
document.addEventListener('change',async e=>{if(e.target.matches('[data-grant]')){const input=e.target,enabled=input.checked;input.checked=!enabled;confirm(enabled?'授予家属权限':'撤回家属权限',enabled?'授权后，家属可以查看并协助处理这类信息。':'撤回后，家属将不能再查看和处理这类信息。已下载或获知的信息无法追回。','grant.set',{scope:input.dataset.grant,enabled});}if(e.target.id==='large-mode'){CarePreferences.setItem('eldercare-large',e.target.checked?'1':'0');render();}});
window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'home';filter='全部';render();});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
window.addEventListener('focus',refresh);
setInterval(()=>{if(document.visibilityState==='visible'&&!dialog.open&&!busy)refresh();},12000);
(async()=>{if(token){try{state=await api('state');role=state.role;render();return;}catch{token=null;}}await enter(role);if(!state)app.innerHTML='<div class="startup">体验记录暂时无法读取，请在浏览器中重新打开页面或清除此网站的数据。</div>';})();
window.addEventListener('storage',event=>{if(event.key==='eldercare-public-demo-v1')refresh();});
if(document.modelContext?.registerTool){
  const lifecycle=new AbortController();
  try{Promise.resolve(document.modelContext.registerTool({name:'start_service_booking',title:'打开养老服务预约',description:'选择示例服务并打开预约确认表单。不会创建订单，必须由访问者确认提交。',inputSchema:{type:'object',properties:{serviceId:{type:'string',enum:['escort','home','meal','visit']}},required:['serviceId'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){if(!state||!input||Object.keys(input).length!==1||!state.services.some(x=>x.id===input.serviceId))throw Error('服务选项无效');if(role==='operator'||(role==='family'&&!state.grants.booking))throw Error('当前视图没有预约权限');go('services');await onAction({dataset:{action:'book',id:input.serviceId}});return {status:'awaiting_user_confirmation',serviceId:input.serviceId};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}
  window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
